// Defines what "compliance readiness" means per framework: a mix of items satisfied by a
// generated document, a populated vendor register, or AI-analyzed uploaded evidence that
// specifically maps to that item (see services/evidenceIntelligence.js). 'unavailable' remains
// as an honest fallback for anything not yet covered by any of the above.
// This is the target checklist gap analysis is scored against.
//
// `why` and `risk` are curated, plain-English explanations — not AI-generated per view. A
// first-time founder looking at "Enable MFA" with no context (the incumbent-tool experience) has
// no way to judge if it matters; these two lines are the AI Compliance Coach's core content,
// hand-written once so they're always available, free, and consistent rather than a per-view LLM
// call that could phrase the same control differently every time someone looks at it.

const GAP_CHECKLIST = {
  iso27001: {
    label: 'ISO 27001',
    items: [
      { key: 'iso_policy', label: 'Information Security Policy', check: { type: 'document', framework: 'iso27001', docType: 'information_security_policy' },
        why: 'This is the master document describing how your company protects data and systems — auditors and enterprise customers ask for it first, before anything else.',
        risk: "Without it, you can't answer \"do you have a security program?\" with anything concrete — deals stall right at the security-questionnaire stage." },
      { key: 'access_control', label: 'Access Control Policy', check: { type: 'document', framework: 'iso27001', docType: 'access_control_policy' },
        why: "Defines who gets access to what, and how that access is granted, reviewed, and revoked (e.g. when someone leaves). It's the single most-checked control in most audits because most breaches start with excess access.",
        risk: "An ex-employee's account left active for months is a real, common audit finding — not a hypothetical." },
      { key: 'incident_response', label: 'Incident Response Plan', check: { type: 'document', framework: 'iso27001', docType: 'incident_response_plan' },
        why: "A step-by-step plan for the first hours of a security incident — who's notified, what gets shut down, who talks to customers.",
        risk: 'Without one, a breach turns into chaos and missed legal deadlines instead of a controlled response.' },
      { key: 'risk_register_doc', label: 'Information Security Risk Register', check: { type: 'document', framework: 'risk_assessment', docType: 'risk_register' },
        why: "A living list of specific risks to your business (e.g. \"single cloud provider,\" \"no MFA on admin accounts\") with how likely and how bad each one is.",
        risk: 'Without it, you\'re managing security by gut feel — auditors read a missing risk register as "nobody has actually thought about what could go wrong here."' },
      { key: 'vendor_policy', label: 'Vendor Risk Assessment Policy', check: { type: 'document', framework: 'risk_assessment', docType: 'vendor_risk_assessment' },
        why: 'The written process for how you evaluate a new vendor\'s security before you sign up with them.',
        risk: "Without it, a vendor's breach becomes your incident too, and you have no paper trail showing you did diligence." },
      { key: 'vendor_register', label: 'Vendor Risk Register (structured)', check: { type: 'vendors' },
        why: 'The actual list of every vendor/tool you use, tiered by risk — a payments processor is riskier than a note-taking app.',
        risk: 'This is usually the first thing an auditor or a customer\'s security team asks for — "show me your vendor list" — and not having one is an instant red flag.' },
      { key: 'audit_evidence', label: 'Audit Evidence Checklist', check: { type: 'document', framework: 'audit_evidence', docType: 'evidence_checklist' },
        why: "A mapped list of what proof you'll need to show a real auditor, tied to each control.",
        risk: 'Without it, audit prep becomes a scramble the week before, instead of something built up quietly all year.' },
      { key: 'asset_register', label: 'Asset Register', check: { type: 'evidence' },
        why: 'A list of what you actually have to protect — servers, laptops, databases, cloud accounts.',
        risk: "You can't secure what you don't know you have; auditors will ask how you know this list is complete." },
      { key: 'security_training', label: 'Security Awareness Training Records', check: { type: 'evidence' },
        why: 'Proof your team has been trained on things like phishing and password hygiene — most breaches start with a person, not a firewall.',
        risk: "It's one of the cheapest controls to have and one of the most commonly missing — an easy finding for an auditor to flag." },
      { key: 'backup_recovery', label: 'Backup & Disaster Recovery Procedure', check: { type: 'evidence' },
        why: "Proof your data is actually backed up and that you've thought through how you'd recover if something failed.",
        risk: '"We think we have backups" is not an acceptable audit answer — it needs to be a documented, tested procedure.' },
    ],
  },
  gdpr: {
    label: 'GDPR',
    items: [
      { key: 'privacy_policy', label: 'Privacy Policy', check: { type: 'document', framework: 'gdpr', docType: 'privacy_policy' },
        why: 'The public-facing document telling users what data you collect and why — legally required the moment you handle any EU personal data.',
        risk: 'Operating without one is a direct GDPR violation, not just a missing nice-to-have.' },
      { key: 'dpa', label: 'Data Processing Agreement', check: { type: 'document', framework: 'gdpr', docType: 'data_processing_agreement' },
        why: 'The contract you sign with any vendor that processes personal data for you (hosting, email, analytics) — GDPR requires this exact paperwork to exist.',
        risk: "Without signed DPAs, you're technically non-compliant every time you use such a vendor, regardless of how secure that vendor actually is." },
      { key: 'ropa', label: 'Record of Processing Activities (ROPA)', check: { type: 'document', framework: 'gdpr', docType: 'ropa' },
        why: 'A structured log of what personal data you process, why, and where it goes — GDPR Article 30 explicitly requires this document to exist.',
        risk: "It's one of the first things a data protection authority asks for in an investigation — not having it is a violation on its own, separate from whatever they were investigating." },
      { key: 'vendor_register', label: 'Sub-processor / Vendor Register', check: { type: 'vendors' },
        why: 'GDPR requires you to know and be able to disclose every sub-processor that touches EU personal data on your behalf.',
        risk: "If a sub-processor mishandles data and you can't show you tracked and vetted them, liability comes back to you." },
      { key: 'breach_procedure', label: 'Data Breach Notification Procedure', check: { type: 'evidence' },
        why: 'GDPR gives you 72 hours to notify authorities after discovering a breach involving personal data — you need a plan before it happens, not during.',
        risk: 'Missing the 72-hour window because you\'re figuring out the process live is a compliance failure on top of the breach itself.' },
      { key: 'dpia', label: 'Data Protection Impact Assessment (DPIA)', check: { type: 'evidence' },
        why: "A formal risk assessment GDPR requires before starting any processing that's likely \"high risk\" to individuals (large-scale profiling, sensitive data, etc.).",
        risk: "Skipping a required DPIA is a standalone violation — you can be non-compliant even if the underlying processing itself is otherwise fine." },
    ],
  },
  cmmc: {
    label: 'CMMC / NIST 800-171',
    items: [
      { key: 'ssp', label: 'System Security Plan (SSP)', check: { type: 'document', framework: 'cmmc', docType: 'system_security_plan' },
        why: 'The foundational CMMC document describing exactly how each required control is implemented in your specific systems — not a generic template, a description of your actual setup.',
        risk: 'No SSP means no CMMC assessment can even start; it\'s the first document any assessor asks for.' },
      { key: 'poam', label: 'Plan of Action & Milestones (POA&M)', check: { type: 'document', framework: 'cmmc', docType: 'poam' },
        why: "For every control you don't fully meet yet, this tracks the specific plan and date to close that gap — CMMC explicitly allows some open items if they're tracked here.",
        risk: 'Without a POA&M, unmet controls just look like non-compliance with no plan — the difference between a yellow flag and a red one.' },
      { key: 'ir_plan', label: 'CMMC Incident Response Plan (72hr DFARS)', check: { type: 'document', framework: 'cmmc', docType: 'incident_response_plan_cmmc' },
        why: 'CMMC/DFARS requires reporting certain cyber incidents to the DoD within 72 hours — this plan is what makes that deadline achievable.',
        risk: 'Missing the mandatory 72-hour DoD reporting window is a contract compliance failure, separate from the security incident itself.' },
      { key: 'vendor_register', label: 'Subcontractor / Vendor Flow-Down Register', check: { type: 'vendors' },
        why: 'CMMC requirements "flow down" to your subcontractors — you have to track which of your own vendors also need to meet CMMC requirements.',
        risk: "A subcontractor that isn't CMMC-aware is a hole in your whole supply chain's compliance, and your prime contract is what's at risk." },
      { key: 'config_baseline', label: 'Configuration Management Baseline', check: { type: 'evidence' },
        why: 'A documented "known good" configuration for your systems, so unauthorized changes can be detected.',
        risk: "Without a baseline, you have no way to prove a system hasn't been tampered with — configuration management is its own named, checked control." },
      { key: 'access_evidence', label: 'Access Control Implementation Evidence', check: { type: 'evidence' },
        why: 'Proof — not just a policy — that access controls are actually enforced: logs, screenshots, IAM configs.',
        risk: 'Assessors distinguish "you wrote a policy" from "you can prove it\'s actually running" — this is the proof.' },
      { key: 'security_training', label: 'Security Awareness Training Records', check: { type: 'evidence' },
        why: 'CMMC/DFARS require documented security awareness training for anyone handling covered defense information.',
        risk: "It's cheap to have and commonly missing — an easy, avoidable finding." },
    ],
  },
  iso42001: {
    label: 'ISO 42001 / AI Governance',
    items: [
      { key: 'aims_policy', label: 'AI Management System Policy', check: { type: 'document', framework: 'iso42001', docType: 'ai_management_system_policy' },
        why: 'The top-level policy defining how your company governs AI systems — who approves them, how risk is assessed, who\'s accountable.',
        risk: 'Without it, "AI governance" is just a phrase in a pitch deck — nothing concrete to show a customer or regulator who asks how you actually manage AI risk.' },
      { key: 'ai_risk_assessment', label: 'AI Risk & Impact Assessment', check: { type: 'document', framework: 'iso42001', docType: 'ai_risk_assessment' },
        why: 'A structured assessment of what could go wrong with each AI system you use or build (bias, hallucination, misuse) and how you mitigate it.',
        risk: 'Regulators and enterprise customers increasingly ask specifically for this — "we\'re careful" isn\'t an answer, a documented assessment is.' },
      { key: 'eu_ai_act', label: 'EU AI Act Readiness Statement', check: { type: 'document', framework: 'iso42001', docType: 'eu_ai_act_readiness' },
        why: 'The EU AI Act classifies AI systems by risk tier (minimal to unacceptable) with different obligations for each — this statement shows you\'ve actually done that classification for your own systems.',
        risk: 'The Act is phasing in through 2026 with real penalties; "we haven\'t looked into it" won\'t be a viable answer once enforcement ramps up.' },
      { key: 'vendor_register', label: 'Third-Party AI/Foundation Model Register', check: { type: 'vendors' },
        why: 'A list of every third-party AI model or API you rely on (e.g. OpenAI, Anthropic) — you inherit some of their risk and need to track it.',
        risk: "If a foundation model provider has an incident or policy change, you need to already know exactly where you're exposed." },
      { key: 'bias_testing', label: 'Bias/Fairness Testing Evidence', check: { type: 'evidence' },
        why: "Proof you've actually tested an AI system for skewed or unfair outcomes across different groups, not just assumed it's fine.",
        risk: 'Unaddressed bias in a customer-facing or hiring-adjacent AI system is both a compliance and a legal liability risk.' },
      { key: 'human_oversight_log', label: 'Human Oversight Checkpoint Log', check: { type: 'evidence' },
        why: "Record of where a human reviews or can override the AI's output — a core requirement for higher-risk AI systems under most AI governance frameworks.",
        risk: "Fully autonomous AI decisions with no human checkpoint is exactly what regulators are targeting first." },
      { key: 'model_monitoring', label: 'Post-Deployment Model Monitoring Records', check: { type: 'evidence' },
        why: "Proof you keep watching an AI system's real-world behavior after launch, not just testing it once before shipping.",
        risk: '"We tested it once" isn\'t governance — models drift and fail in production in ways pre-launch testing doesn\'t catch.' },
    ],
  },
};

module.exports = { GAP_CHECKLIST };
